# Site settings
title: 思维净化    				  	#你博客的标题
SEOTitle: 梁江俊的博客 | 梁江俊 Blog    	 #显示在浏览器上搜索的时候显示的标题
header-img: img/post-bg-rwd.jpg  	#显示在首页的背景图片
email: 2308232417@qq.com	
description: "为者常成,而行者常至" 			 #网站介绍
keyword: "nlp,deep learning ,math" #关键词
url: " https://xuan_yun.gitee.io"          # 这个就是填写你的博客地址
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog' # 这个我们不用填写
github_repo: "https://gitee.com/xuan_yun/xuan_yun.gitee.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "为者常成,而行者常至"
sidebar-avatar: /img/梁江俊.jpg      # 你的个人头像 这里你可以改成我在img文件夹中的两张备用照片 img/avatar-m 或 avatar-g



# SNS settings
RSS: false
# weibo_username:     qiubaiying
zhihu_username:    xuanyun
# github_username:    Alkane0050
# facebook_username:  baiying.qiu.7
jianshu_username:   1e7b57d303b5
#twitter_username:   qiubaiying




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: qiubaiying

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: c8268810037919cbcdc7                             #生成的clientID
  clientSecret: 2d290c9bd2de03ef6adef746043fd5edd90cc2d7    #生成的clientSecret
  repo: bogtalk    #仓库名称
  owner: Jiangjun-liang    #github用户名
  admin: Jiangjun-liang
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: 420e8fd242d23d87ff1d7dfba930ba86

# Google Analytics
# ga_track_id: 'UA-140085164-1'            # Format: UA-xxxxxx-xx
# ga_domain: alkane0050.fun               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
   {
        title: "微信公众号：炫云云",

    },{
        title: "知乎",
        href: "https://www.zhihu.com/people/xuan-yun-77-83"
    },{
        title: "简书",
        href: "https://www.jianshu.com/u/1e7b57d303b5"
    },{
        
    }

]
